user: &user
  plugins:
    root: 'plugins.user_plugins'
    include: Null
    exclude: Null

  addons:
    wheel_userids:
      - 1698923450

sessions: # name: {options}
  cattobot: {<<: *user}

# Notes:
#
# All plugin root directories should be in plugins directory

# Examples:
#
### Your own client sets ###
#custom: &custom
#  <<: *default # This line ensures non recursive inheritance from default client set
#  plugins:
#    root:
#      - 'plugins.extra_plugins'
#    include:
#      - 'extra_plugin'
#    exclude:
#      - 'unwanted'
#
#  addons:
#    wheel_userids:
#      - 12312421
#      - 25235423
#      - 21424111
#      - ...
#
#sessions:
#  something: {<<: *custom}
### Your own client sets ###

### A single value to modify ###
#extra_plugins: &extra_plugins
#  root: 'extra_plugins'
#
#sessions:
#  something: {<<: *default, *extra_plugins}
# OR
#  something: {<<: *default, plugins: {root: 'extra_plugins'}}
### A single value to modify ###
